# Generated by Django 4.2.17 on 2025-11-01 16:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
